inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 125
  Exclude: 
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/*'
  
Style/NumericLiterals:
  Exclude:
    - 'db/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

